### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by kisaragychihaya**
Tested on RTX3080+CUDA11.4+ubuntu18.04

### CODE REVIEW

**Comment by nagadomi** [comment]
Thank you for PR.
I think the time zone setting is unnecessary because it is not appropriate for many people.
Perhaps you can change it by specifying TZ environment variable (I am not very familiar with Docker).
```
docker run -e TZ=Asia/Shanghai ...
```

**Comment by kisaragychihaya** [comment]
> Thank you for PR. I think the time zone setting is unnecessary because it is not appropriate for many people. Perhaps you can change it by specifying TZ environment variable (I am not very familiar with Docker).
> 
> ```
> docker run -e TZ=Asia/Shanghai ...
> ```

Time zone setting is triggered by apt。。。。I am finding some method to avoid the Time zone setting

**Comment by kisaragychihaya** [comment]
TZ setting is removed

**Comment by nagadomi** [comment]
I will merge this PR, but will merge it after Ubuntu 22.04 is released for 21.10.
(Currently I do not have a version of Ubuntu where  NVIDIA Container Toolkit can be installed)

**Comment by nagadomi** [comment]
It may be a good idea to add all architectures that can be supported.
It will take a lot of time to compile, but it will work everywhere without JIT compilation.
related to https://github.com/nagadomi/waifu2x/issues/272 https://github.com/nagadomi/waifu2x/pull/138

**Comment by kisaragychihaya** [comment]
Now is using SASS code instead of PTX. And Removed the old  device support below SM50 due to CUDA11

**Comment by nagadomi** [comment]
Is it really necessary to build cmake from github source code?(in Dockerfile)

**Comment by kisaragychihaya** [comment]
> Is it really necessary to build cmake from github source code?(in Dockerfile)

Because Cmake v3.18 which is installed by  apt is failed to build lltcggie-caffe, I try to build Cmake 3.22 from source It work

**Comment by kisaragychihaya** [comment]
> Is it really necessary to build cmake from github source code?(in Dockerfile)

Now it is using the binary from [https://cmake.org/download/](https://cmake.org/download/)

**Comment by kisaragychihaya** [comment]
When I use the prebuilt binary instead of build form src , I get this error (And the version of cmake in ubuntu18.04 from apt is too low to build
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "waifu2x-caffe" in directory /usr/src/waifu2x-caffe
    linked by target "caffe" in directory /usr/src/waifu2x-caffe/caffe/src/caffe
```

**Comment by nagadomi** [comment]
Ok, I recall encountering that problem before.
But why ubuntu 18.04 instead of ubuntu 20.04? Is there some dependency problem?

**Comment by kisaragychihaya** [comment]
> Ok, I recall encountering that problem before. But why ubuntu 18.04 instead of ubuntu 20.04? Is there some dependency problem?

yes,ubuntu20.04 use opencv4.2 ,which is fail to build [caffe](https://github.com/nagadomi/caffe.git) when I wrote this DockerFile (can not find opencv4.x by PKG_CONFIG）. But Now I am fix these error in this [PR](https://github.com/nagadomi/caffe/pull/3#issuecomment-1115891239)

**Comment by nagadomi** [comment]
I have merged your PR for lltcggie-caffe and updated `CUDA_ARCH` in `Makefile.conf.example-ubuntu`.
Could you now change to ubuntu20.04 and remove the unnecessary processes (cmake build and sed for Makefile.conf)?
Or, I can do it myself after the merge this PR.

**Comment by kisaragychihaya** [comment]
Done, And Tested

**Comment by nagadomi** [comment]
Thank you, merged.
Added several example commands. https://github.com/nagadomi/waifu2x-caffe-ubuntu/blob/ubuntu/INSTALL-linux.md#docker

**Comment by nagadomi** [comment]
The current code can also be built on ubuntu 22.04.

**Pull request merged**
